document.addEventListener("DOMContentLoaded",function(){triggerModals();animateModalImages();scrollHeroImage();toggleMobileMenu();elementsInViewport();animateDetailsElement();});function triggerModals(){const triggerEls=document.querySelectorAll(".modal-trigger");const closeEls=document.querySelectorAll(".modal__close");const bodyEl=document.querySelector("body");triggerEls.forEach(el=>{let type=el.getAttribute("data-type");let id=el.getAttribute("data-id");let parentType=el.getAttribute("data-parent-type");let parentId=el.getAttribute("data-parent-id");el.addEventListener("click",function(){if(parentType&&parentId){openModal(el,type,id,parentType,parentId);}else{openModal(el,type,id,false,false);}});});closeEls.forEach(el=>{el.addEventListener("click",function(){closeModal();});});document.addEventListener("keyup",function(e){if(27===e.keyCode&&"Escape"===e.key){closeModal();}});bodyEl.addEventListener("click",function(e){if(e.target.classList.contains("modal")||e.target.classList.contains("modal__inner")||e.target.classList.contains("modal__close-wrapper")){closeModal();}});function openModal(el,type,id,parentType,parentId){let modal=document.querySelector(`.modal[data-type='${type}'][data-id='${id}']`);if(modal!==null){if(parentType&&parentId){closeModal(false)
setTimeout(function(){modal.classList.add("modal--visible");},300);modal.setAttribute("data-parent-type",parentType);modal.setAttribute("data-parent-id",parentId);}else{modal.classList.add("modal--visible");}
modal.setAttribute("aria-hidden",false);focusLock.on(modal);bodyEl.classList.add("modal-is-visible");}}
function closeModal(){let activeModal=document.querySelector(".modal--visible");if(activeModal!==null){let type=activeModal.getAttribute("data-type");let id=activeModal.getAttribute("data-id");let parentType=activeModal.getAttribute("data-parent-type");let parentId=activeModal.getAttribute("data-parent-id");let triggerEl=document.querySelector(`.modal-trigger[data-type='${type}'][data-id='${id}']`);activeModal.classList.remove("modal--visible");activeModal.setAttribute("aria-hidden",true);focusLock.off(activeModal);if(parentType&&parentId){let triggerParentEl=document.querySelector(`.modal-trigger[data-type='${parentType}'][data-id='${parentId}']`);triggerParentEl.focus();}else{triggerEl.focus();}
activeModal.removeAttribute("data-parent-type");activeModal.removeAttribute("data-parent-id");bodyEl.classList.remove("modal-is-visible");animateModalImages(true);}}}
function animateModalImages(destroy=false){const modalEls=document.querySelectorAll(".modal");modalEls.forEach(el=>{function flagged(){this.isScrolled=true;}
function preventClick(event){event.preventDefault();event.stopImmediatePropagation();}
let galleryEl=el.querySelector(".modal__images--drag");if(galleryEl!==null&&window.innerWidth>=959){let activeClass="modal__images--drag-active";const options={grid:0,limit:{x:null,y:[1,1]},onDragStart:function(){galleryEl.classList.add(activeClass);galleryEl.classList.remove("modal__images--drag-animating");},onDragEnd:function(){galleryEl.classList.remove(activeClass);},onDrag:function(element,x,y,event){let wrapperEl=el.querySelector(".modal__content");let wrapperBounds=wrapperEl.getBoundingClientRect();let rightEl=el.querySelector(".modal__right");let rightBounds=rightEl.getBoundingClientRect();let leftPos=parseInt(element.style.width,10);let offsetRight=(wrapperBounds.x-rightBounds.x)*-1;let offsetLeft=(wrapperBounds.x-(window.innerWidth-leftPos))*-1;if(x>offsetRight){dragEl.set(offsetRight,y);galleryEl.classList.remove("modal__images--drag-finish");}else if(x<offsetLeft){dragEl.set(offsetLeft,y);galleryEl.classList.add("modal__images--drag-finish");}}};let dragEl=new Draggable(galleryEl,options);function moveGalleryPanel(){return;}
galleryEl.addEventListener("mousedown",function(){galleryEl.style.cursor="grabbing";galleryEl.addEventListener('mousemove',flagged);});galleryEl.addEventListener("mouseup",function(e){galleryEl.style.cursor="grab";if(this.isScrolled){galleryEl.removeEventListener('click',moveGalleryPanel);galleryEl.addEventListener('click',preventClick);}else{galleryEl.addEventListener('click',moveGalleryPanel);galleryEl.removeEventListener('click',preventClick);}
this.isScrolled=false;galleryEl.removeEventListener('mousemove',flagged);});if(destroy===false){window.addEventListener("mousewheel",function(e){let threshold=20;if(el.classList.contains("modal--visible")){let wrapperEl=el.querySelector(".modal__content");let wrapperBounds=wrapperEl.getBoundingClientRect();let rightEl=el.querySelector(".modal__right");let element=el.querySelector(".modal__images--drag");let elementBounds=element.getBoundingClientRect();let rightBounds=rightEl.getBoundingClientRect();let leftPos=elementBounds.width;let offsetRight=(wrapperBounds.x-rightBounds.x)*-1;let offsetLeft=(wrapperBounds.x-(window.innerWidth-leftPos))*-1;let pos=dragEl.get();let newPosX;if(e.wheelDeltaY>=-5&&e.wheelDeltaY<=5){if(e.wheelDeltaX<0){if(pos.x>offsetLeft){galleryEl.classList.add(activeClass);newPosX=Math.round(pos.x-threshold);dragEl.set(newPosX,0);}}else{if(pos.x<offsetRight){newPosX=Math.round(pos.x+threshold);dragEl.set(newPosX,0);if(newPosX===Math.round(offsetRight)){galleryEl.classList.remove(activeClass);}}}}}else{dragEl.destroy;}});}else{let wrapperEl=el.querySelector(".modal__content");let wrapperBounds=wrapperEl.getBoundingClientRect();let rightEl=el.querySelector(".modal__right");let rightBounds=rightEl.getBoundingClientRect();let initialPos=Math.round((wrapperBounds.x-rightBounds.x)*-1);galleryEl.classList.remove(activeClass);dragEl.set(initialPos,0);}}});}
function scrollHeroImage(){const heroImageEl=document.querySelector(".intro__hero-image");window.addEventListener("scroll",throttle(function(){let elementInViewport=isElementXPercentInViewport(heroImageEl,20);let activeClass="in-viewport--true";if(elementInViewport){heroImageEl.classList.add(activeClass);}else{heroImageEl.classList.remove(activeClass);}},1000));const isElementXPercentInViewport=function(el,percentVisible){let
rect=el.getBoundingClientRect(),windowHeight=(window.innerHeight||document.documentElement.clientHeight);return!(Math.floor(100-(((rect.top>=0?0:rect.top)/+-rect.height)*100))<percentVisible||Math.floor(100-((rect.bottom-windowHeight)/rect.height)*100)<percentVisible)};}
function toggleMobileMenu(){const mobileMenuEl=document.querySelector(".header__mobile-controls");const bodyEl=document.querySelector("body");const headerEl=document.querySelector(".header");const anchorEls=document.querySelectorAll(".nav__anchor");const logoEl=document.querySelector(".logo__anchor");const activeClass="mobile-menu-open";mobileMenuEl.addEventListener("click",function(){if(bodyEl.classList.contains(activeClass)){bodyEl.classList.remove(activeClass);focusLock.off(headerEl);}else{bodyEl.classList.add(activeClass);focusLock.on(headerEl);anchorEls.forEach(el=>{el.addEventListener("click",function(){bodyEl.classList.remove(activeClass);focusLock.off(headerEl);});});logoEl.addEventListener("click",function(){bodyEl.classList.remove(activeClass);focusLock.off(headerEl);});}});}
function initMap(){let popups=[];let mapMarkers=[];let markerElement=document.querySelector(".map__map");let markers=JSON.parse(markerElement.getAttribute("data-pins"));function addMarkerInfo(){for(var i=0;i<markers.length;i++){var contentString='<div class="map__popup">'+markers[i].placeName+'</div>';let marker;const baseUrl=location.protocol+'//'+location.host+location.pathname;marker=new google.maps.Marker({position:markers[i].LatLng[0],map:map,icon:`${baseUrl}/wp-content/themes/and-apartments/images/icon-dot-grey.svg`,type:markers[i].type,svg:markers[i].icon,zIndex:1});mapMarkers.push(marker);const infowindow=new google.maps.InfoWindow({content:contentString,maxWidth:200});marker.infoWindowOpen=false;if(window.innerWidth>959){marker.addListener("mouseover",function(){infowindow.open(marker.get("map"),marker);marker.setIcon(`${baseUrl}/wp-content/themes/and-apartments/images/icon-dot-white.svg`);marker.setZIndex(2);});marker.addListener("mouseout",function(){infowindow.close(marker.get("map"),marker);marker.setIcon(`${baseUrl}/wp-content/themes/and-apartments/images/icon-dot-grey.svg`);marker.setZIndex(1);});}else{marker.addListener("click",function(){closeOtherInfo(marker);if(marker.infoWindowOpen===true){infowindow.close(marker.get("map"),marker);marker.infoWindowOpen=false;marker.setIcon(`${baseUrl}/wp-content/themes/and-apartments/images/icon-dot-grey.svg`);marker.setZIndex(1);}else{infowindow.open(marker.get("map"),marker);marker.infoWindowOpen=true;marker.setIcon(`${baseUrl}/wp-content/themes/and-apartments/images/icon-dot-white.svg`);marker.setZIndex(2);}
popups[0]=infowindow;});map.addListener("click",function(){if(popups.length>0){closeOtherInfo();}});}}}
const svgAmpersand={path:"M19.63,17.19l-15-13c-1-.88-1.56-1.6-1.52-2.17L3,2.21a3.72,3.72,0,0,0-.58,4.71A7.64,7.64,0,0,0,3.9,8.65l11.42,9.83c2.37,2.07,4.54,2.1,6.51.13l.17-.17h-.27a5.62,5.62,0,0,1-2.1-1.25m-12.48,0-4.29-3.7c-1-.88-1.56-1.59-1.53-2.17l-.17.17A3.74,3.74,0,0,0,.59,16.2a7.19,7.19,0,0,0,1.52,1.73l.73.55c2.38,2.07,4.55,2.1,6.51.14l.17-.17H9.25a5.78,5.78,0,0,1-2.1-1.26M10.87,0H6L8.21,1.89c1,.88,1.56,1.59,1.53,2.17l.17-.17a3.73,3.73,0,0,0,1-3.89m7.25,11-.17.17c0-.58-.47-1.29-1.53-2.17L14.24,7.09h4.84a3.73,3.73,0,0,1-1,3.89",fillColor:"#fff",fillOpacity:1,strokeWeight:0,scale:2.6,anchor:new google.maps.Point(11,12)};const coords={lat:-35.273100,lng:149.131927};const map=new google.maps.Map(document.getElementById("map"),{zoom:17,center:coords,streetViewControl:false,disableDefaultUI:true,clickableIcons:false,styles:[{"featureType":"all","elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#000000"},{"lightness":40}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#000000"},{"lightness":16}]},{"featureType":"all","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":13}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":13},{"weight":1.2}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":13}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":13}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":20},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":10}]},],});addMarkerInfo();new google.maps.Marker({position:{lat:-35.270950,lng:149.132900},map,icon:svgAmpersand});filterEls=document.querySelectorAll(".map__control");mapFilters=[];filterEls.forEach(el=>{el.addEventListener("click",function(e){el.classList.toggle("map__control--active");let type=el.getAttribute("data-map-filter");if(el.classList.contains("map__control--active")){mapFilters.push(type);filterMapMarkers(map,mapFilters);}else{const index=mapFilters.indexOf(type);if(index>-1){mapFilters.splice(index,1);}
filterMapMarkers(map,mapFilters);}});});function filterMapMarkers(map){for(let i=0;i<mapMarkers.length;i++){if(mapFilters.length>0){if(mapFilters.includes(mapMarkers[i].type)){mapMarkers[i].setMap(map);}else{mapMarkers[i].setMap(null);}}else{mapMarkers[i].setMap(map);}}}
function closeOtherInfo(marker=false){let baseUrl=location.protocol+'//'+location.host+location.pathname;if(popups.length>0){popups[0].set("marker",null);popups[0].close();popups.length=0;}
for(var i=0;i<mapMarkers.length;i++){if(marker!==mapMarkers[i]){mapMarkers[i].infoWindowOpen=false;mapMarkers[i].setIcon(`${baseUrl}/wp-content/themes/and-apartments/images/icon-dot-grey.svg`);mapMarkers[i].setZIndex(1);}}}}
function throttle(fn,wait){var time=Date.now();return function(){if((time+wait-Date.now())<0){fn();time=Date.now();}}}
function elementsInViewport(){enterView({selector:".in-viewport",enter:function(el){el.classList.add("in-viewport--true");},exit:function(el){el.classList.remove("in-viewport--true");},offset:0.4});}
function animateDetailsElement(){class Accordion{constructor(el){this.el=el;this.summary=el.querySelector('summary');this.content=el.querySelector('.modal__details-content');this.animation=null;this.isClosing=false;this.isExpanding=false;this.summary.addEventListener('click',(e)=>this.onClick(e));}
onClick(e){e.preventDefault();this.el.style.overflow='hidden';if(this.isClosing||!this.el.open){this.open();}else if(this.isExpanding||this.el.open){this.shrink();}}
shrink(){this.isClosing=true;const startHeight=`${this.el.offsetHeight}px`;const endHeight=`${this.summary.offsetHeight}px`;if(this.animation){this.animation.cancel();}
this.animation=this.el.animate({height:[startHeight,endHeight]},{duration:200,easing:'ease-out'});this.animation.onfinish=()=>this.onAnimationFinish(false);this.animation.oncancel=()=>this.isClosing=false;}
open(){this.el.style.height=`${this.el.offsetHeight}px`;this.el.open=true;window.requestAnimationFrame(()=>this.expand());}
expand(){this.isExpanding=true;const startHeight=`${this.el.offsetHeight}px`;const endHeight=`${this.summary.offsetHeight + this.content.offsetHeight}px`;if(this.animation){this.animation.cancel();}
this.animation=this.el.animate({height:[startHeight,endHeight]},{duration:400,easing:'ease-out'});this.animation.onfinish=()=>this.onAnimationFinish(true);this.animation.oncancel=()=>this.isExpanding=false;}
onAnimationFinish(open){this.el.open=open;this.animation=null;this.isClosing=false;this.isExpanding=false;this.el.style.height=this.el.style.overflow='';}}
document.querySelectorAll('details').forEach((el)=>{new Accordion(el);});}